[build]
  command = "CI=false npm run build"
  functions = "functions"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"