[build]
  command = "CI=false npm run build"
  functions = "functions"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: https://raw.githubusercontent.com; connect-src 'self' https://api.coinmarketcap.com https://api.uniswap.org https://*.infura.io wss://relay.walletconnect.com wss://relay.walletconnect.org https://*.alchemyapi.io https://cloudflare-ipfs.com https://*.uniswap.org https://tokens.coingecko.com https://api.coingecko.com https://verify.walletconnect.com https://verify.walletconnect.org https://explorer-api.walletconnect.com https://cloudflare-eth.com https://gateway.ipfs.io https://api.thegraph.com;"
    Access-Control-Allow-Origin = "*"